### ISSUE TITLE
Training code release

### ISSUE THREAD

**Issue by Ling27** [JiejiangWu/FaceG2E#1]

**Comment by Ling27** [comment]
Hi @JiejiangWu 

Wonder that u have plan to release the training code?

**Comment by JiejiangWu** [comment]
Hi @Ling27 :
Thanks for interests in our work.
The training of the texture diffusion network is based on the code example of training stable diffusion from Diffuser:
[train_text_to_image.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py)

The training data in our work consists of two parts, the publicly available dataset, and our own scanned dataset. Unfortunately, our scanned dataset cannot be open-sourced with the license issue. While you can try to train a texture diffusion network with only publicly available datasets, i.e.,: [FFHQ-UV](https://github.com/csbhr/FFHQ-UV), [FaceScape](https://github.com/zhuhao-nju/facescape).

**Comment by Ooodkkk** [comment]
Hello. May I ask if it is only necessary to train the part train_text_to_image.py?
