### ISSUE TITLE
How to train FaceG2E?

### ISSUE THREAD

**Issue by luoclab** [JiejiangWu/FaceG2E#2]
If I want to train this model,What is I need to do?

**Comment by JiejiangWu** [comment]
Hi @luoclab ,
Our FaceG2E is basicly a training-free method, it relies on pretrained 2D diffusion model to generate and edit 3D faces. One can download the pretrained model and generate 3D faces with text prompts directly.
The only part involving training is the texture diffusion model (we have released the pretrained weights). You can train it by you own follow the instruction:  [issue#1](https://github.com/JiejiangWu/FaceG2E/issues/1#issuecomment-2295758603)
